# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
             --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_DB: booking_system
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
    ports:
      - '54321:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:80"